### ISSUE TITLE
User Auth Review

### ISSUE THREAD

**Issue by RSchaubeck** [RSchaubeck/soundcloud_clone#2]
Hey Justin, my user auth MVP is ready for review.

**Comment by jmeyer90** [comment]
Tasks to be completed

- The login / signup forms in Soundcloud slide down into the page.
- The demo login should login a user, not just populate the fields.
- Even though this isn't on Soundcloud, the login form should have a button to render the signup form and the signup form should have a button to render the login form.
- Where Soundcloud has a disclaimer on their forms, you should have text there and it can say whatever you want.

Note: This can wait until a later MVP, but the main page should look like the main page on Soundcloud: no Navbar, links and buttons appear over an image, serachbar, button to upload songs, and a footer with links to your linkedIn, gihub, etc.
